# config files
defaults:
  - dataset: semantickitti_mac
  - model: randlanet
  - pipeline: semseg_ext
  - _self_

# run args
mode: train  # train+eval | train | eval
debug: false  # runs compact debug setup

hydra:
  run:
    dir: .
  output_subdir: null
