defaults:
  - dataset: semantickitti_mac
  - model: randlanet
  - pipeline: semseg_ext
  - _self_

mode: train  # train+eval (default) | train | eval
debug: false

hydra:
  run:
    dir: .
  output_subdir: null
