# config files
defaults:
  - dataset: semantickitti
  - model: randlanet
  - pipeline: semseg_ext
  - _self_

# run args
mode: train+eval  # train+eval | train | eval
debug: false  # runs compact debug setup
clean: false  # cleans logs of old runs (ckpts & stdout)

hydra:
  run:
    dir: .
  output_subdir: null
