dataset:
  name: SemanticKITTIFlat
  dataset_path: /data/datasets/sample_datasets/public_datasets/semantic_kitti
  cache_dir: ./logs/cache  # uses dataset cache if path is given
  class_weights: [55437630, 320797, 541736, 2578735, 3274484, 552662, 184064,
    78858, 240942562, 17294618, 170599734, 6369672, 230413074, 101130274,
    476491114, 9833174, 129609852, 4506626, 1168181]  # TODO: class weighting strategy
model:
  name: RandLANetFlat
  ckpt_path: #
  ignored_label_inds: [0]  # original label IDs  # TODO: map to train labels in loss functions
  dim_output: [16, 64, 128, 256]  # TODO: define feature space
pipeline:
  name: SemSegExt
  # TODO: default optimizer, LR and scheduler!
  optimizer:  
    lr: 0.001
  scheduler_gamma: 0.9886
  batch_size: 2
  val_batch_size: 2
  train_sum_dir: ./logs/train_logs/
  max_epoch: 100
  save_ckpt_freq: 5
  # TODO: refactor config of evals, logging and visualization (find solution for final result visu)
  summary:
    record_for: ['train', 'val']
    max_pts: 15000  # downsampling 
    use_reference: false 
    max_outputs: 2
  projection:  # TODO: refactor to general "visu" config
    enabled: true
    record_for: ['train', 'valid']
    image_size: [640, 640]
    axes: [0, 1]      # XY-top view
    depth_axis: 2